apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: bot
    env: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
      env:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
        env: 
    spec:
      containers:
      - name: worker
        image: 
        env:
          - name: ENV
            value: 
        resources:
          requests:
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "300Mi"
            cpu: "500m"
        